### ISSUE TITLE
[FEAT] Transfer email generation

### ISSUE THREAD

**Issue by nolandanz** [VATUSA/current#57] opened 2021-08-27 14:16 UTC
### What is your new feature idea or request?

Transfer email should be generated when division staff submits transfer request for controllers. Not sure if it's a bug or not implemented, but BB submitted a transfer on behalf of a controller and there was no email sent that said I had a pending transfer.

**Comment by bnahin** [comment] 2021-08-28 17:10
Duplicate of #39.

**Closed by bnahin** 2021-08-28 17:10 UTC
